In [ ]:
Question 1:

Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24


In [3]:
import math
C = 50
H = 30
input_str = input("Enter comma-separated values of D: ")
D_list = [int(x) for x in input_str.split(',')]
result_list = []
for D in D_list:
    Q = round(math.sqrt((2 * C * D) / H))
    result_list.append(str(Q))
print(','.join(result_list))

Enter comma-separated values of D:  100,150,180


18,22,24


In [ ]:
Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡¬Y-1.
Example
Suppose the following inputs are given to the program:
3,5
Then, the output of the program should be:
[[0, 0, 0, 0, 0], 
[0, 1, 2, 3, 4],
[0, 2, 4, 6, 8]] 


In [1]:
import numpy as np

X = int(input("Enter the number of rows: "))
Y = int(input("Enter the number of columns: "))

result = np.zeros((X, Y), dtype=int)

for i in range(X):
    for j in range(Y):
        result[i][j] = i * j

print(result)


Enter the number of rows:  3
Enter the number of columns:  5


[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [ ]:
Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.
Suppose the following input is supplied to the program:
without,hello,bag,world
Then, the output should be:
bag,hello,without,world


In [4]:
words = input("Enter a comma-separated sequence of words: ")
word_list = words.split(",")
word_list.sort()
sorted_words = ",".join(word_list)
print(sorted_words)


Enter a comma-separated sequence of words:  without,hello,bag,world


bag,hello,without,world


In [ ]:
Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.
Suppose the following input is supplied to the program:
hello world and practice makes perfect and hello world again
Then, the output should be:
again and hello makes perfect practice world


In [2]:
words = input("Enter a sequence of words: ")
word_list = words.split()
unique_words = list(set(word_list))
sorted_words = sorted(unique_words)
result = ' '.join(sorted_words)
print(result)


Enter a sequence of words:  the name is xyz and sur name is pqr


and is name pqr sur the xyz


In [ ]:
Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the following input is supplied to the program:
hello world! 123
Then, the output should be:
LETTERS 10
DIGITS 3


In [5]:
sentence = input("Enter a sentence: ")
letter_count = 0
digit_count = 0
for i in sentence:
    if i.isalpha():  
        letter_count += 1
    elif i.isdigit(): 
        digit_count += 1
print("LETTERS", letter_count)
print("DIGITS", digit_count)


Enter a sentence:  My name is xyz123


LETTERS 11
DIGITS 3


In [ ]:
Question 6:
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example

If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1


In [6]:
import re
passwords = input("Enter comma separated passwords: ")
password_list = passwords.split(",")
valid_passwords = []
for password in password_list:
    if len(password) >= 6 and len(password) <= 12:
        if re.search("[a-z]", password) and re.search("[A-Z]", password) and re.search("[0-9]", password) and re.search("[$#@]", password):
            valid_passwords.append(password)
print(",".join(valid_passwords))


Enter comma separated passwords:  ABd1234@1,a F1#,2w3E*,2We3345


ABd1234@1
