In [ ]:
1.	Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])
result = matrix1 + matrix2

print(result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
2.	Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])
result = matrix1 * matrix2

print(result)


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
3.	Write a Python Program to Transpose a Matrix?

In [3]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
transposed_matrix = matrix.T

print(transposed_matrix)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
4.	Write a Python Program to Sort Words in Alphabetic Order?

In [5]:
def sort_words(words):
    word_list = words.split()
    word_list.sort()
    sorted_words = ' '.join(word_list)
    
    return sorted_words
words = "i am learning data science from iNeuron"

a= sort_words(words)
print(a)


am data from i iNeuron learning science


In [ ]:
5.	Write a Python Program to Remove Punctuation From a String?

In [16]:
def remove_punctuation(text):
    punctuation = "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
    no_punct = ''
    for i in text:
        if i not in punctuation:
            no_punct += i
    
    return no_punct

text = "Hello sir, how are you doing?"

no_punct_text = remove_punctuation(text)
print(no_punct_text)


Hello sir how are you doing
